version: '3'
services:

  cp_pg_server:
    image: carpool/pg_server
    container_name: cp_pg_server
    environment:
      - MAILGUNKEY=CHANGE_ME
      - TWILIO_NUMBER=CHANGE_ME
      - TWILIO_AUTH_TOKEN=CHANGE_ME
      - TWILIO_ACCOUNT_SID=CHANGE_ME
    volumes:
      - pgdata:/var/lib/postgresql/data
    # ports:
    #   - 5432:5432

  cp_adminer:
    image: adminer
    restart: always
    container_name: cp_adminer
    depends_on:
      # use "cp_pg_server" as hostname to establish connection to postgres in cp_pg_server container
      - cp_pg_server
    links:
      - cp_pg_server
    ports:
      # Don't export the unprotected adminer to the outside
      - 127.0.0.1:8080:8080

  cp_api:
    image: carpool/api
    container_name: cp_api
    depends_on:
      - cp_pg_server
    links:
      - cp_pg_server
    environment:
      - PGUSER=carpool_web
      - PGPASSWORD=null
      - PGHOST=cp_pg_server
      - PORT=3030
      - PGDATABASE=LIVE
    ports:
      - 3030:3030

  cp_matching:
    image: carpool/matching
    container_name: cp_matching
    depends_on:
      - cp_pg_server
    links:
      - cp_pg_server
    environment:
      - PGUSER=carpool_app
      - PGPASSWORD=null
      - PGHOST=cp_pg_server
      - PGDATABASE=LIVE

volumes:
  pgdata:
