version: '2.1'

services:
  cp-test:
    # image: selenium/standalone-chrome

    # this images supports viewing test browser using a vnc viewer
    image: selenium/standalone-chrome-debug
    # image: selenium/standalone-firefox

    ports:
      - '5900:5900'

    depends_on:
      - cp-nodejs
      - cp-pg-server
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3 # may not be needed

  cp-front-end:
    build:
      context: ../../jekyllDev/
      args:
        REPO: https://github.com/voteamerica/voteamerica.github.io
        BRANCH_NAME: master

    # this setting causes /bin/bash to wait on input, not exit immediately
    tty: true
    ports:
      - '4000:4000'
    depends_on:
      - cp-nodejs
      - cp-pg-server

    # https://jekyllrb.com/docs/usage/
    # NOTE: .yml file () needs to contain IP addresses for this network (not the usual localhost). Entrypoint script does this, too.
    # command: jekyll serve -H 0.0.0.0 --watch --config /_config-local-ip.yml
    # command: jekyll serve -H 0.0.0.0 --watch --source /usr/src/app/frontend --destination /usr/src/app/frontend/_site --config /_config-local-ip.yml
    # command: jekyll serve -H 10.5.0.4 --watch --source /usr/src/app/frontend --destination /usr/src/app/frontend/_site --config /_config-local-ip.yml
    # command: jekyll serve --watch --source /usr/src/app/frontend --config /_config-local-ip.yml
    entrypoint: /expo-start-ip.sh

    networks:
      vpcbr:
        ipv4_address: 10.5.0.4 # probably not needed, but keeps things in sync

  cp-nodejs:
    build:
      context: ../../nodeApp/
      args:
        REPO: https://github.com/voteamerica/backend
        BRANCH_NAME: master
    image: carpool

    depends_on:
      - cp-pg-server
    # command: bash
    stdin_open: true
    tty: true
    environment:
      - PGPASSWORD=pwd
      - PGHOST=10.5.0.6
      - JWT_SECRET=test_weak_secret
      - CSV_LOCAL=true
    ports:
      - '8000:8000'
    links:
      - cp-pg-server

    networks:
      vpcbr:
        ipv4_address: 10.5.0.5

  cp-pg-server:
    build:
      context: ../../pg-auto
      args:
        REPO: https://github.com/voteamerica/backend
        BRANCH_NAME: master
    image: pgres-cp
    ports:
      - '5433:5432'

    networks:
      vpcbr:
        ipv4_address: 10.5.0.6

  cp-pg-client:
    build:
      context: ../../pg-client
      args:
        REPO: https://github.com/voteamerica/backend
        BRANCH_NAME: master
    image: pg-client
    depends_on:
      - cp-pg-server

    # command: bash
    stdin_open: true
    tty: true
    environment:
      - PGUSER=postgres
      # - PGUSER=carpool_web
      - PGDATABASE=carpoolvote
      - PGPASSWORD=pwd
      - PGHOST=10.5.0.6

    networks:
      vpcbr:
        ipv4_address: 10.5.0.7

  cp-test-runner:
    build:
      context: ../../nightwatch/
      args:
        REPO: https://github.com/voteamerica/backend
        BRANCH_NAME: master
    image: nightwatch

    depends_on:
      - cp-test
    # command: /bin/bash
    # command: /run-tests.sh match2

    stdin_open: true
    tty: true

    networks:
      vpcbr:
        ipv4_address: 10.5.0.8

# this supports networks with static ip addresses
# http://stackoverflow.com/questions/39493490/provide-static-ip-to-docker-containers-via-docker-compose
networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
